project:
  type: website

website:
  title: "About me"
  navbar:
    left:
      - href: index.md
        text: Home
      - href: layer8/index.md
        text: Layer 8
      - href: resume/index.md
        text: Resume
      - href: info/index.md
        text: Info

format:
  html:
    theme:
      # See: https://quarto.org/docs/output-formats/html-themes.html
      light: default
      dark: solar
    css: styles.css
    toc: true



